data_loader:
  batch_size: 32
  workers: 4
  split_ratio: 0.8
training:
  model: "unet"
  optimizer:
    lr: 1e-3
  max_epochs: 2
  limits_batches:
    train: 1.0
    val: 1.0
checkpoints:
  dirpath: "models/"
