image_transformations:
  image_size: 256

data_loader:
  batch_size: 16
  workers: 4
  split_ratio: 0.8

training:
  model: "unet"
  optimizer:
    lr: 1e-3
  max_epochs: 200
  limits_batches:
    train: 1.0
    val: 1.0

checkpoints:
  dirpath: "models/"
  filename: "unet_bs=16_img_size=256_epoch=58-val_loss=1.09093-val_mean_iou=0.43380.ckpt"
